fix(utils/plots.py): fix AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox
or getlength instead.
https://github.com/tensorflow/models/issues/11040
pip install Pillow==9.5.0
-i https://pypi.tuna.tsinghua.edu.cn/simple